### PR TITLE
add scripts, docker support and fix bugs to help building more smoothly.

### LINKED ISSUE #9: Do we need to add envionment variables manually after running 3rdtools.sh?
After 3rd-party packages are installed, is it necessary to add envionment variables manually? The build stage of plato suffers from "undefined reference to" error.
err

### LINKED ISSUE #10: noma.h: No such file or directory
I am on a ubuntu 16.04 LTS, and I installed all dependencies and executed `bash  3rdtools.sh install`  successfully.

```
BAZEL_LINKOPTS=-static-libstdc++ CC=/usr/bin/mpicxx bazel build example/...
```

All things went well until I executed the command below

```
BAZEL_LINKOPTS=-static-libstdc++ CC=/usr/bin/mpicxx LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/3rd/hadoop2/lib bazel test --test_env=LD_LIBRARY_PATH plato/...
```

the output shows a file named numa.h is missing, and I found that file does not exist in the project, anyone help?

```bash
In file included from plato/graph/base.cc:22:0:
./plato/graph/base.hpp:36:18: fatal error: numa.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 446.216s, Critical Path: 1.59s
INFO: 3 processes: 3 linux-sandbox.
FAILED: Build did NOT complete successfully
//plato/algo/bnc/test:test_bnc                                        NO STATUS
//plato/algo/cgm/test:test_cgm                                        NO STATUS
//plato/algo/cnc/test:test_cnc                                        NO STATUS
//plato/algo/hanp/test:test_hanp                                      NO STATUS
//plato/algo/hyperanf/test:test_hyperanf                              NO STATUS
//plato/algo/nstepdegrees/test:test_nstepdegrees                      NO STATUS
//plato/engine/test:walk                                              NO STATUS
//plato/graph/state/test:allgather_state                              NO STATUS
//plato/graph/state/test:dense_state                                  NO STATUS
//plato/graph/state/test:sparse_state                                 NO STATUS
//plato/graph/state/test:vertex_cache                                 NO STATUS
//plato/graph/structure/test:bcsr                                     NO STATUS
//plato/graph/structure/test:cbcsr                                    NO STATUS
//plato/graph/structure/test:dcsc                                     NO STATUS
//plato/graph/structure/test:edge_cache                               NO STATUS
//plato/graph/structure/test:hnbbcsr                                  NO STATUS
//plato/graph/structure/test:tcsr                                     NO STATUS
//plato/graph/test:message_passing                                    NO STATUS
//plato/graph/test:parsers                                            NO STATUS
//plato/graph/test:structure                                          NO STATUS
//plato/parallel/test:broadcast                                       NO STATUS
//plato/parallel/test:bsp                                             NO STATUS
//plato/parallel/test:parallel                                        NO STATUS
//plato/util/test:aliastable                                          NO STATUS
//plato/util/test:archive                                             NO STATUS
//plato/util/test:bitmap                                              NO STATUS
//plato/util/test:intersection                                        NO STATUS
//plato/util/test:libsvm                                              NO STATUS
//plato/util/test:mmap_alloc                                          NO STATUS
//plato/util/test:object_buffer                                       NO STATUS
//plato/util/test:test_hyperloglog                                    NO STATUS
//plato/util/test:thread_local_object                                 NO STATUS

FAILED: Build did NOT complete successfully
```

### LINKED ISSUE #11: FAILED: Build did NOT complete successfully
### the situation I met is
```bash
➜  plato git:(master) BAZEL_LINKOPTS=-static-libstdc++ CC=/usr/bin/mpicxx bazel build example/...
INFO: Analyzed 24 targets (39 packages loaded, 14033 targets configured).
INFO: Found 24 targets...
INFO: Deleting stale sandbox base /home/jsy/.cache/bazel/_bazel_jsy/336f117599031580e40b679ad0dfd7d6/sandbox
ERROR: /home/jsy/github/plato/example/BUILD:151:1: C++ compilation of rule '//example:bfs_simple' failed (Exit 1) mpicxx failed: error executing command 
  (cd /home/jsy/.cache/bazel/_bazel_jsy/336f117599031580e40b679ad0dfd7d6/sandbox/linux-sandbox/1/execroot/__main__ && \
  exec env - \
    PATH=/home/jsy/.sdkman/candidates/scala/current/bin:/home/jsy/.sdkman/candidates/maven/current/bin:/home/jsy/.sdkman/candidates/kotlin/current/bin:/home/jsy/.sdkman/candidates/groovy/current/bin:/home/jsy/bin:/usr/share/node-v10.16.0-linux-x64/bin:/usr/share/jdk1.8.0_211/bin:/usr/share/go//bin:/home/jsy/.cargo/bin:/home/jsy/bin:/home/jsy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/mpicxx -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/example/_objs/bfs_simple/bfs_simple.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/example/_objs/bfs_simple/bfs_simple.pic.o' -fPIC -D__DUALMODE_DEBUG__ -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -Ibazel-out/k8-fastbuild/bin/3rd/glog/_virtual_includes/glog -Ibazel-out/k8-fastbuild/bin/3rd/gflags/_virtual_includes/gflags -Ibazel-out/k8-fastbuild/bin/3rd/yas/_virtual_includes/yas -Ibazel-out/k8-fastbuild/bin/3rd/hadoop2/_virtual_includes/hdfs-dynamic -Ibazel-out/k8-fastbuild/bin/3rd/jni/_virtual_includes/jni -isystem 3rd/boost/include -isystem bazel-out/k8-fastbuild/bin/3rd/boost/include -isystem plato/graph -isystem bazel-out/k8-fastbuild/bin/plato/graph -isystem plato/util -isystem bazel-out/k8-fastbuild/bin/plato/util -isystem plato/util/libcuckoo -isystem bazel-out/k8-fastbuild/bin/plato/util/libcuckoo -isystem plato/graph/state -isystem bazel-out/k8-fastbuild/bin/plato/graph/state -isystem plato/parallel -isystem bazel-out/k8-fastbuild/bin/plato/parallel -isystem plato/graph/partition -isystem bazel-out/k8-fastbuild/bin/plato/graph/partition -isystem 3rd/jni/include/linux -isystem bazel-out/k8-fastbuild/bin/3rd/jni/include/linux -isystem plato/graph/structure -isystem bazel-out/k8-fastbuild/bin/plato/graph/structure -isystem plato/algo/bfs -isystem bazel-out/k8-fastbuild/bin/plato/algo/bfs -isystem plato/engine -isystem bazel-out/k8-fastbuild/bin/plato/engine -g -O2 -Werror -g -fPIC -static-libstdc++ -static-libgcc -fopenmp -Wall '-std=c++11' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c example/bfs_simple.cc -o bazel-out/k8-fastbuild/bin/example/_objs/bfs_simple/bfs_simple.pic.o)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox: mpicxx failed: error executing command 
  (cd /home/jsy/.cache/bazel/_bazel_jsy/336f117599031580e40b679ad0dfd7d6/sandbox/linux-sandbox/1/execroot/__main__ && \
  exec env - \
    PATH=/home/jsy/.sdkman/candidates/scala/current/bin:/home/jsy/.sdkman/candidates/maven/current/bin:/home/jsy/.sdkman/candidates/kotlin/current/bin:/home/jsy/.sdkman/candidates/groovy/current/bin:/home/jsy/bin:/usr/share/node-v10.16.0-linux-x64/bin:/usr/share/jdk1.8.0_211/bin:/usr/share/go//bin:/home/jsy/.cargo/bin:/home/jsy/bin:/home/jsy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/mpicxx -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/example/_objs/bfs_simple/bfs_simple.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/example/_objs/bfs_simple/bfs_simple.pic.o' -fPIC -D__DUALMODE_DEBUG__ -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -Ibazel-out/k8-fastbuild/bin/3rd/glog/_virtual_includes/glog -Ibazel-out/k8-fastbuild/bin/3rd/gflags/_virtual_includes/gflags -Ibazel-out/k8-fastbuild/bin/3rd/yas/_virtual_includes/yas -Ibazel-out/k8-fastbuild/bin/3rd/hadoop2/_virtual_includes/hdfs-dynamic -Ibazel-out/k8-fastbuild/bin/3rd/jni/_virtual_includes/jni -isystem 3rd/boost/include -isystem bazel-out/k8-fastbuild/bin/3rd/boost/include -isystem plato/graph -isystem bazel-out/k8-fastbuild/bin/plato/graph -isystem plato/util -isystem bazel-out/k8-fastbuild/bin/plato/util -isystem plato/util/libcuckoo -isystem bazel-out/k8-fastbuild/bin/plato/util/libcuckoo -isystem plato/graph/state -isystem bazel-out/k8-fastbuild/bin/plato/graph/state -isystem plato/parallel -isystem bazel-out/k8-fastbuild/bin/plato/parallel -isystem plato/graph/partition -isystem bazel-out/k8-fastbuild/bin/plato/graph/partition -isystem 3rd/jni/include/linux -isystem bazel-out/k8-fastbuild/bin/3rd/jni/include/linux -isystem plato/graph/structure -isystem bazel-out/k8-fastbuild/bin/plato/graph/structure -isystem plato/algo/bfs -isystem bazel-out/k8-fastbuild/bin/plato/algo/bfs -isystem plato/engine -isystem bazel-out/k8-fastbuild/bin/plato/engine -g -O2 -Werror -g -fPIC -static-libstdc++ -static-libgcc -fopenmp -Wall '-std=c++11' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c example/bfs_simple.cc -o bazel-out/k8-fastbuild/bin/example/_objs/bfs_simple/bfs_simple.pic.o)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
In file included from example/bfs_simple.cc:26:0:
example/bfs_simple.cc:42:18: error: 'input_validator_registered' defined but not used [-Werror=unused-variable]
 DEFINE_validator(input, &string_not_empty);
                  ^
bazel-out/k8-fastbuild/bin/3rd/gflags/_virtual_includes/gflags/gflags/gflags.h:139:23: note: in definition of macro 'DEFINE_validator'
     static const bool name##_validator_registered = \
                       ^
cc1plus: all warnings being treated as errors
INFO: Elapsed time: 27.966s, Critical Path: 23.45s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

```
### some details of my environment as below

**about bazel**
```bash
➜  # about bazel
➜  plato git:(master) command -v bazel
/home/jsy/bin/bazel

➜  ~ # bazel version runs well in my home folder
➜  ~ bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.26.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:35:14 2019 (1559032514)
Build timestamp: 1559032514
Build timestamp as int: 1559032514

➜ #  but bazel doesn't show it's version in my plato code base directory
➜  plato git:(master) pwd 
/home/jsy/github/plato

➜  plato git:(master) bazel version
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=169
INFO: Reading rc options for 'version' from /home/jsy/github/plato/.bazelrc:
  Inherited 'common' options: --color=yes --verbose_failures --strip=never
ERROR: Unrecognized option: --verbose_failures
```
**about mpicxx**
```bash
➜  # about my mpicxx

➜  plato git:(master) command -v mpicxx
/usr/bin/mpicxx
➜  plato git:(master) mpicxx --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  plato git:(master) mpicxx -v
mpicxx for MPICH version 3.2
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
```
**about my os**
```bash
➜  ~ uname -a
Linux jsy-ubuntu 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

➜  ~ screenfetch 
                          ./+o+-       jsy@jsy-ubuntu
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.15.0-66-generic
           .++ .:/++++++/-.+sss/`      Uptime: 6h 21m
         .:++o:  /++++++++/:--:/-      Packages: 2223
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.1.1
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: Unity 7.4.5
 /+++//+:`oo+o               /::--:.   WM: Compiz
 \+/+o+++`o++o               ++////.   WM Theme: Radiance
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Radiance [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: ubuntu-mono-light
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i3-8100 CPU @ 3.6GHz
           .o:`.syhhhhhhh/.oo++o`      RAM: 11784MiB / 15775MiB
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      

```

### LINKED ISSUE #17: cannot find -lstdc++ when building examples
when building examples with the script below
`BAZEL_LINKOPTS=-static-libstdc++ CC=mpicxx bazel build example/...`
an error is raised

> Use --sandbox_debug to see verbose messages from the sandbox
> /usr/bin/ld.gold: error: cannot find -lstdc++

### LINKED ISSUE #21: Provide a build environment on Dockerhub

### LINKED ISSUE #22: Build Failed: link to libunwind error.
when running BAZEL_LINKOPTS=-static-libstdc++ CC=/usr/bin/mpicxx  bazel build example/...
### I met
`WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/command.profile.gz'
INFO: Analyzed 24 targets (42 packages loaded, 14017 targets configured).
INFO: Found 24 targets...
INFO: Deleting stale sandbox base /home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/sandbox
ERROR: /home/tian/wzb/plato/example/BUILD:20:1: Linking of rule '//example:function_call' failed (Exit 1) mpicxx failed: error executing command 
  (cd /home/tian/.cache/bazel/_bazel_tian/d46c134286fdbb1c2928eea0643ff387/sandbox/linux-sandbox/6/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/tian/bin \
    PWD=/proc/self/cwd \
  /usr/bin/mpicxx @bazel-out/k8-fastbuild/bin/example/function_call-2.params)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_Ux86_64_getcontext'
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_init_local'
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_get_reg'
3rd/glog/lib/libglog.a(libglog_la-utilities.o):utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_step'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 165.786s, Critical Path: 154.06s
INFO: 2 processes: 2 linux-sandbox.
FAILED: Build did NOT complete successfully`

### And I have installed  libunwind

### PR DESCRIPTION
**Pull request by xuguruogu**
1. add docker support.
2. add travis-ci support.
3. support run pagerank locally.
4. remove unused files from 3td dir.
5. change something to avoid gcc bugs of gcc5.

closes #21, closes #22, closes #11, closes #17, closes #6, closes #10, closes #9

### CODE REVIEW

File: 3rdtools.sh [hunk 1]
```diff
@@ -8,7 +8,7 @@ function clean_exec {
   cmd=$*
   eval $cmd
   retcode=$?
-  if [[ $retcode != 0 ]]; then
+  if [ $retcode != 0 ]; then
```
Comment (skyssj) [inline 3rdtools.sh]: use` [ $retcode -ne 0 ]` instead ??

Comment (xuguruogu) [reply 3rdtools.sh]: > use` [ $retcode -ne 0 ]` instead ??

done
